OPM-34 resolved: fixed some Option-related bugs
(1) The addition of support for pending values introduced
    a regression whereby diffs were created for every value
    set to None, even if the value had previously been set
    to None. Due to (2), this meant that saving an object
    with a value set to None, making a change to the object
    but leaving the value set to None and saving the change,
    and then loading the object and accessing the None threw
    a NoSuchMethodError.

(2) From the beginning, the Mongo persistence of an Option
    changing to None (forwards) or to Some (backwards) was
    the same as the persistence for a value being removed
    from the model entirely (forwards) or being added to the
    model (backwards). This meant that saving an object with
    a value set to Some(_), changing the value to None and
    saving the object, and then loading the object and
    accessing the value threw a NoSuchMethodError.

Change-Id: I5ac2f434fd0829073867719ea02a5c87fb6dedef
Reviewed-on: https://gerrit.gilt.com/17670
Tested-by: jenkins bot <jenkins@hudson.qa.corp.gilt.com>
Reviewed-by: Eric Bowman <ebowman@gilt.com>